name: 'grackle_watch'
version: '1.0.0'
profile: 'grackle_watch'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  grackle_watch:
    staging:
      +materialized: view
    gold:
      +materialized: table
      fct_observations:
        +materialized: table      